apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/postgres.yaml
  - manifests/secret.yaml
images:
  - name: zanaad/ping-pong-app
    newName: zanaad/ping-pong-app
    newTag: latest

    