apiVersion: v1
kind: Service
metadata:
  name: ping-pong-app-svc
  namespace: log-pong
spec:
  type: ClusterIP
  selector:
    app: ping-pong-app
  ports:
    - port: 3456
      protocol: TCP
      targetPort: 8082

