name: Deploy Pingpong

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        run: |
          docker build -t zanaad/pingpong:${{ github.sha }} .
          docker push zanaad/pingpong:${{ github.sha }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update Image Tag in kustomization.yaml
        run: kustomize edit set image pingpong-image=zanaad/pingpong:${{ github.sha }}

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yaml'
          message: Update pingpong image ${{ github.sha }}
